version: 3.9

orbs:
  node: circleci/node@22.11.0

jobs:
  run-app:
    docker:
      - image: cimg/node:22.17
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run Node App
          command: node index.js

workflows:
  main-workflow:
    jobs:
      - run-app
